spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:~/test;MODE=MySQL
    username: sa
    driver-class-name: org.h2.Driver

logging:
  level:
    org.hibernate.type: trace
    org.hibernate.sql: debug
