name: Android TEST CI

on:
  pull_request:
    branches: [ "develop" ]
    paths:
      - "android/**"
    
permissions:
  checks: write
  pull-requests: write
  
jobs:
  android-test:

    runs-on: ubuntu-latest
    env:
      working-directory: ./android

    steps:
    - uses: actions/checkout@v3
    
    - name: Java JDK 17 세팅
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: local properties 생성
      run: touch local.properties
      working-directory: ${{ env.working-directory }}
      
    - name: local properties 세팅
      env:
        BASE_URL: ${{ secrets.BASE_URL }}
        GIT_HUB_URL: ${{ secrets.GIT_HUB_URL }}
      run: 
        echo. "BASE_URL=\"$BASE_URL\"" >> local.properties
        echo. "GIT_HUB_URL=\"$GIT_HUB_URL\"" >> local.properties
      working-directory: ${{ env.working-directory }}
      
    - name: google-services json 생성
      run: touch google-services.json
      working-directory: ${{ env.working-directory }}/app
      
    - name: google-services json 세팅
      env:
        GOOGLE: ${{ secrets.GOOGLE }}
      run: echo "$GOOGLE" >> google-services.json
      working-directory: ${{ env.working-directory }}/app
      

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: ${{ env.working-directory }}
      
    - name: test 진행
      run: ./gradlew --info test
      working-directory: ${{ env.working-directory }}
      
    - name: test 결과
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        junit_files: |
          ${{ env.working-directory }}/app/build/test-results/*Debug*/*.xml
          ${{ env.working-directory }}/domain/build/test-results/test/*.xml

